# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c0d3bee9-c275-42b0-a48d-036e3a76c509";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c0d3bee9-c275-42b0-a48d-036e3a76c509".device = "/dev/disk/by-uuid/c0d3bee9-c275-42b0-a48d-036e3a76c509";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9E24-E927";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b1875c1b-14a3-49f3-8251-432758c05041"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
