# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c14aabe8-387a-4e79-b586-89253a6185e1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c14aabe8-387a-4e79-b586-89253a6185e1".device = "/dev/disk/by-uuid/c14aabe8-387a-4e79-b586-89253a6185e1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CC76-0D45";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-2ef9f8bc-c173-433f-ac87-74dd74155df1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
