vim.lsp.enable("lua_ls")
vim.lsp.enable("gopls")
vim.lsp.enable("pyright")
vim.lsp.enable("nil_ls")
vim.lsp.enable("clangd")
vim.lsp.enable("rust_analyzer")
vim.lsp.enable("html")
vim.lsp.enable("cssls")
